upstream myproject {
    server swt-intern-wee-engine:8000;
}

server {

    listen 80;

    server_name default_server;

    root /;

    index index.html index.htm;
    error_page 404 /index.html;

    charset utf-8;
    gzip on;
    gzip_proxied any;
    gzip_types
        text/css
        text/javascript
        text/xml
        text/plain
        application/javascript
        application/x-javascript
        application/json;

    location /webapp {
        alias /webapp;
        try_files $uri $uri/ /webapp/index.html;
    }

    location /webapp2 {
        alias /webapp2;
        try_files $uri $uri/ /webapp2/index.html;
    }

    location / {
        return 301 /webapp;
    }

    location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|woff2|woff|otf|ttf)$ {
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
    }

    location ~* \.(?:css|js)$ {
        try_files $uri =404;
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
    }

    location /api/v1/ {
        proxy_pass http://myproject/;
    }

}
